version: "3.7"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-8.0
    restart: always                      
    environment:
      MYSQL_DATABASE: 'museu_dbtemplate'  
      MYSQL_USER: 'root'                
      MYSQL_PASSWORD: 'password'          
      MYSQL_ROOT_PASSWORD: 'password'    
    ports:
      - '3306:3306'                       
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:




